### ISSUE TITLE
头脑王者游戏进入不了

### ISSUE THREAD

**Issue by G1aRe** [game-helper/weixin#20]

**Comment by zhuweiyou** [comment]
终端打印的 LOG 发一下。

**Comment by G1aRe** [comment]
![default](https://user-images.githubusercontent.com/17924947/35468574-e156da40-035b-11e8-9fdf-e3553ea80180.png)

**Comment by G1aRe** [comment]
![default](https://user-images.githubusercontent.com/17924947/35468575-f0d07f94-035b-11e8-8a51-ecd31f448c32.png)

**Comment by G1aRe** [comment]
![default](https://user-images.githubusercontent.com/17924947/35468590-3bf10692-035c-11e8-82d8-a07d670213dd.png)

**Comment by zhuweiyou** [comment]
需要先执行 `npm i` 安装依赖（文档上有说明哦），就不会报 Cannot find module xxx 了。

从你的截图上看，先检查下证书是否安装好。

另外后续还有 LOG 打印吗？把小程序进程杀掉，重新进入看看

**Comment by G1aRe** [comment]
没有后续LOG打印  重新进也不行

**Comment by zhuweiyou** [comment]
你的 nodejs 版本多少？`node -v` 查看

随便试试打开别的网页，能否正常打开？

**Comment by G1aRe** [comment]
这样是不是手机通过电脑上网？

**Comment by G1aRe** [comment]
打不开

**Comment by G1aRe** [comment]
v8.9.4

**Comment by zhuweiyou** [comment]
如果打不开别的网页的话，那是你的代理有问题。
正常来说应该可以打开的，检查下你的 IP 对不对。

**Comment by G1aRe** [comment]
是电脑在局域网内的IP吧？

**Comment by zhuweiyou** [comment]
是的，只要配置正确了，log 会有输出的

**Comment by zhuweiyou** [comment]
@G1aRe 现在问题解决了吗？

**Comment by G1aRe** [comment]
没有， 哎 找不到问题在哪

**Comment by zhuweiyou** [comment]
头脑王者已经被封了，这个先关了，后续有问题在开
