### ISSUE TITLE
包你懂我怎么不准了，原来用还是好的，是不是更新了。

### ISSUE THREAD

**Issue by cuicanxk** [game-helper/weixin#23]

**Comment by zhuweiyou** [comment]
我最近没玩，有可能是小程序更新了。

不准是什么情况？终端有打印信息吗

**Comment by cuicanxk** [comment]
就是答案不是正确答案，打印信息是下面这个吗。

> anyproxy --intercept --ignore-unauthorized-ssl --rule=index.js

[AnyProxy Log][2018-01-30 12:50:11]: Http proxy started on port 8001
[AnyProxy Log][2018-01-30 12:50:11]: web interface started on port 8002
[AnyProxy Log][2018-01-30 12:50:27]: received request to: GET pms.mb.qq.com/rsp2
04
[AnyProxy Log][2018-01-30 12:50:27]: received request to: GET pms.mb.qq.com/rsp2
04
[AnyProxy Log][2018-01-30 12:50:28]: received request to: POST oth.eve.mdt.qq.co
m:8080/analytics/upload?rid=e26f0f7f9d1ccafd&sid=1dc9b3920e2dd4ed5840f1a65d0f7cf
a
[AnyProxy Log][2018-01-30 12:50:28]: received request to: POST oth.eve.mdt.qq.co
m:8080/analytics/upload?rid=bc0586c9759b7ee5&sid=1dc9b3920e2dd4ed5840f1a65d0f7cf
a
[AnyProxy Log][2018-01-30 12:50:28]: received https CONNECT request servicewecha
t.com
[AnyProxy Log][2018-01-30 12:50:28]: will forward to local https server
[AnyProxy Log][2018-01-30 12:50:28]: [internal https]proxy server for servicewec
hat.com established
[AnyProxy Log][2018-01-30 12:50:30]: received https CONNECT request minapp.vwvvw
v.com
[AnyProxy Log][2018-01-30 12:50:30]: received https CONNECT request minapp.vwvvw
v.com
[AnyProxy Log][2018-01-30 12:50:30]: will forward to local https server
[AnyProxy Log][2018-01-30 12:50:30]: [internal https]proxy server for minapp.vwv
vwv.com established
[AnyProxy Log][2018-01-30 12:50:30]: will forward to local https server
[AnyProxy Log][2018-01-30 12:50:30]: [internal https]proxy server for minapp.vwv
vwv.com established
[AnyProxy Log][2018-01-30 12:50:30]: received request to: GET minapp.vwvvwv.com/
minapp/answer/question/7H7ymQ2XZXMHfoFglo
[AnyProxy Log][2018-01-30 12:50:30]: received request to: GET minapp.vwvvwv.com/
config/minappnotify
我吃火锅最喜欢的蘸料是？答案:香油
我喜欢几个人去旅行？答案:独自旅行
以下自然现象中我最想看哪个？答案:极光
我是很喜欢养宠物的人吗？答案:是的，养过宠物
我会因为朋友的伤心事而难过吗？答案:会
我认为到海边最好的事情是……？答案:冲浪或者潜水
我在假期会为自己安排旅游吗？答案:会
我平常喜欢喷香水吗？答案:喜欢
我最喜欢什么颜色的头发？答案:亚麻色
我怕鬼吗？答案:很害怕

**Comment by zhuweiyou** [comment]
答案是全错吗？

**Comment by cuicanxk** [comment]
不是 试了2个  一个题目3个对的 另一个题目5个对的

**Comment by zhuweiyou** [comment]
等我有空的时候看看是不是小程序更新了。

**Comment by zhuweiyou** [comment]
![image](https://user-images.githubusercontent.com/8413791/35550680-8ceceeb4-05c6-11e8-883a-40e5064cf438.png)


刚测试了一个，没有问题呀

**Comment by DistanceLi** [comment]
还有一个类似包你懂我的小程序叫你懂我吗可以用吗

**Comment by zhuweiyou** [comment]
@DistanceLi  没有搜索到这个小程序哦

**Comment by DistanceLi** [comment]
@zhuweiyou 嗯嗯那是个网页不是小程序，还有现在好像默认返回a的答案了

**Comment by zhuweiyou** [comment]
这个关了哈，有问题再开
