### ISSUE TITLE
请教一下“跳一跳”的上传分数加密算法是怎么破解出来的？

### ISSUE THREAD

**Issue by lkspc** [game-helper/weixin#25]
“跳一跳”刚出来的时候我也抓包看过，有个上传分数的接口，是加了密的，加密后是一长串字符。也没有头绪怎么破解，能请教一下怎么做到的吗

**Comment by zhuweiyou** [comment]
目前提供的几个辅助中，大部分都是从源码里找到的加密方法。

前段时间有爆出下载源码的漏洞，可以直接下载 zip 包，很多人都下了，现在已经被微信封了。

不过还有别的办法，可拿到任意小程序源码，方法我没有公开过，不然容易封，就不透露了。

**Comment by lkspc** [comment]
感谢解答
