### ISSUE TITLE
我最在行  题目能按照分类来吗？另外题目也不全

### ISSUE THREAD

**Issue by chucklu** [game-helper/weixin#27]
我没有用程序，仅仅是看题库的。
我最在行里面的题目，没有进行分类啊。

另外，题库更新，目前(2018-02-12)来看是三天之前的。
我搜索了一下，郁郁累累的出处。没有发现这个题目，所以，题库还是不全啊。

〖出处〗《乐府诗集·杂曲歌辞二·**悲歌**》：“思念故乡，**郁郁累累**。

**Comment by zhuweiyou** [comment]
题库肯定一直在更新了，可以自行爬取，这边不可能天天来更新题库的。

是直接对 “全能王” 进行爬的，应该会有各种题

**Comment by Tangtonton** [comment]
好像自行爬行的，都是重复的题目，跟pk对战的题目库不一样呢？

**Comment by hxk123456** [comment]
请问您们这个程序怎么下载，怎么使用呀。我是小白能学会吗

**Comment by hobmgcode** [comment]
废了 没题库 都是扯淡

**Comment by hxk123456** [comment]
以前能用吗，现在不能用了是吗

**Comment by zhuweiyou** [comment]
@hxk123456  可以用

**Comment by zhuweiyou** [comment]
题库不全的问题，刚增加了答案自动百度搜索，而不是提交随机答案了，应该能提升不少胜率。

这边暂时没工夫去经常爬库了，可自行爬。

至于数据库里的分类，个人认为没有什么必要，题目是唯一的，拿题目去查询的。
