### ISSUE TITLE
Connection dropped by remote peer.

### ISSUE THREAD

**Issue by hobmgcode** [game-helper/weixin#28]
【我最在行】
 
![baidushurufa_2018-2-12_14-26-57](https://user-images.githubusercontent.com/16664245/36085455-df0f55f8-1000-11e8-874a-42b6c1ed3479.png)

**Comment by zhuweiyou** [comment]
上下文 多截点，复制文本吧。

**Comment by hobmgcode** [comment]
![baidushurufa_2018-2-12_14-51-44](https://user-images.githubusercontent.com/16664245/36085937-44f9efa6-1004-11e8-979c-7db4525b5e59.png)

**Comment by hobmgcode** [comment]
v8.5.0 ? 升9看看

**Comment by zhuweiyou** [comment]
暂时看不出什么问题，多试几次也一样吗？

今天下午回家过年了，没空看代码了。

得明年了

**Comment by hobmgcode** [comment]
明年 = =！ 好吧。过年好
每次都这样

**Comment by zhuweiyou** [comment]
我开号试了一下，报错一样，初步判断是 WSS 的参数变了

年后回来更新下

**Comment by hobmgcode** [comment]
凉凉

**Comment by NicholasXia** [comment]
已经更新完毕了~~~添加ws header即可。😆

**Comment by zhuweiyou** [comment]
@NicholasXia  欢迎 pr

**Comment by Freezind** [comment]
@NicholasXia 能详细说下吗

**Comment by zhuweiyou** [comment]
抽空更新了一下 https://github.com/game-helper/weixin/commit/538ba399826973b764c0ea6f7aadb657cd9e8da6

可以用了 

@hobmgcode 
@Freezind

**Comment by Freezind** [comment]
@zhuweiyou 
问题fixed了。
但是现在打完一局之后还是会被提示Connection dropped by remote peer.
