### ISSUE TITLE
抓到的https是加密的

### ISSUE THREAD

**Issue by Tangtonton** [game-helper/weixin#29]
我最在行 用fiddler 抓https包，url是 https://puzzle-gateway.zaih.com/pauthp/jwt 。
内容是加密的，json只有 access_token和account_id。。。
我已经安装了fiddler的证书插件，PC和Android都安装了生成的证书，但还是无法解密。

**Comment by KilluaChen** [comment]
这个地址能获取到`access_token`和`account_id`就可以了,你是指什么是加密的?

**Comment by Tangtonton** [comment]
明白了，我是Text里看到Encrypted_data ，以为没有解密到。。其实只要 access_token和account_id 就可以用了。
谢谢！
