### ISSUE TITLE
分类索引功能似乎没用

### ISSUE THREAD

**Issue by Tangtonton** [game-helper/weixin#30]
分类索引不管怎么改，都是 春节 分类。0也是春节分类
无法定位 全能王 了。。

**Comment by zhuweiyou** [comment]
找下 game.js 在拿到 id 之前打印下列表，看下全能王是哪个索引……老哥过年还玩这个啊

**Comment by Tangtonton** [comment]
定位是通过 我的擂台 的索引，不是全部擂台。。
小号还没玩过 全能王，所以定位不到。。。。
谢谢

**Comment by zhuweiyou** [comment]
这块年后改成命令行问答模式，输入要排位的索引，就没这个问题了

**Comment by zhuweiyou** [comment]
把列表列出

**Comment by Tangtonton** [comment]
打印出来发现theme id 好像是随机的。。

**Comment by zhuweiyou** [comment]
加个find ,  用 name 匹配下全能王
