### ISSUE TITLE
程序中提示“没有体力”，获取 accesst_token 时返回数据异常 ，详情 

### ISSUE THREAD

**Issue by iwanttodo** [game-helper/weixin#33]
![image](https://user-images.githubusercontent.com/19567697/36401977-1964006c-1616-11e8-8af2-ac12126fcb79.png)

但是事实是我确实还有>5的体力，刚出现这个问题的时候，我怀疑是 access_token 过期 了，所以重新去 https://puzzle-gateway.zaih.com/pauthp/jwt 抓包，结果返回的数据异常

> POST /pauthp/jwt HTTP/1.1
charset: utf-8
Accept-Encoding: gzip
referer: https://servicewechat.com/wx75152d01bd4220d1/22/page-frame.html
authorization: Basic cHV6emxlOmtKdEhhZ3plVmRrOWU4UUNaWWxKU2swdk0yT2o=
content-type: application/json
User-Agent: Mozilla/5.0 (Linux; Android 5.1.1; 2014813 Build/LMY47V; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/57.0.2987.132 MQQBrowser/6.2 TBS/043906 Mobile Safari/537.36 MicroMessenger/6.6.3.1260(0x26060339) NetType/4G Language/zh_CN MicroMessenger/6.6.3.1260(0x26060339) NetType/4G Language/zh_CN
Content-Length: 631
Host: puzzle-gateway.zaih.com
Connection: Keep-Alive

{"encrypted_data":"rgmkSgxG/onwlpIEmZYm7cHkuFsHwewFfVI091sIkXFn3IivWU0PaQxKWNbab0VMwVP/K1zXHPzIK4p7L0c84Juh0qWjJWejVPAxKP4PRzeHu1XUG5VHYqk0cTPTwitIEBlV7O2qig2bJ9n8OMR7VTbCERUANwXEe1n5M/gLX3V8WU2zA3g0S2jI42yncHmInSSyL88Nhx/uO2wRc0cnJG1dS4KEMaKmZAxVXrOJTNHTT+knP5eirkoisyXDHLaidPJxokl0q+Rr89iqFHItQ5zzweihqsC4HmolqfojAa/GfA4m3uOP2/QaeTC0t+h+1SeBSJMiGse9hcFb42Iq6eJmVlupzcFN5byUCvkVXDYoQN674AtpQVwyz3EeZWQvJrRvPvudqP2YjDdN+agt8rC6ForR/zdszZ1Qnshm8Jud9c0C+UZ18d7eyWcoWJr2d3lNdvR+h9CUfKcMZTLgwP1BRL8VhhnLAfN6XjFJ6Hn6+R4bTpWJaEBdBTBg1tkaPQSVfJ7CveHl7kIApBQEMw==","iv":"BtDqmy/RebcyQmHpnkuGKg==","code":"013ju5qY1XpY1U0ZQWqY1mNqqY1ju5qC"}HTTP/1.1 200 OK
Date: Tue, 20 Feb 2018 00:06:44 GMT
Content-Type: application/json
Content-Length: 303
Connection: keep-alive
x-amzn-RequestId: eefa284a-15d1-11e8-a837-a3739e6b9ca1
Access-Control-Allow-Origin: *
X-Amzn-Trace-Id: Root=1-5a8b6693-7f32850c2abb16fffe16e297

{"stackTrace": [["/var/task/json_web_token.py", 122, "create_jwt_token", "is_validated, account = validate_user(username, password, code)"], ["/var/task/json_web_token.py", 113, "validate_user", "raise Unauthorized('account_abnormal')"]], "errorType": "Unauthorized", "errorMessage": "account_abnormal"}

是不是账号被封了？

**Comment by zhuweiyou** [comment]
这是账号被封了…… 看最后一句，账号不正常，换号玩吧。。

**Comment by iwanttodo** [comment]
还是不行，重装微信也不行
卡在了授权上
还是谢谢你

**Comment by zhuweiyou** [comment]
肯定不行 已经封号了 😂

**Comment by iwanttodo** [comment]
他是怎么判断账号异常的？

**Comment by uusift** [comment]
@iwanttodo 你是单线程还是多开？我多开被封了。

**Comment by iwanttodo** [comment]
@uusift 我多开过

**Comment by zhuweiyou** [comment]
应该是每次都 200 分…… 可以加入一些 setTimeout 延迟答题，和故意输的机制，比如赢四题输一题啥的

**Comment by uusift** [comment]
@zhuweiyou 是不是参数 delay？ 再哪里设置的？
直接 await好像不行？

**Comment by zhuweiyou** [comment]
引一下 common 下的 timeout.js 就可以 await 啦

在发送答案之前
```js
await timeout(xxx毫秒)
```

**Comment by zhuweiyou** [comment]
还可以 random 随机下延迟的值 比如 一秒到五秒里 随机。然后赢几题 故意 输一题 之类的。就要额外做一些逻辑了

**Comment by Freezind** [comment]
@zhuweiyou await timeout 了5000多ms，但返回的分数还是200......

**Comment by zhuweiyou** [comment]
@Freezind  那是因为玩游戏有动画时间 现在直接拿数据 更快。你改成十几秒试一下 应该不是 200 了……

**Comment by Freezind** [comment]
@zhuweiyou 似乎是因为在我这跑delay 1000 比1s快得多......数改大了确实可以了

**Comment by zhuweiyou** [comment]
那不应该，你可以简单写个 js 测试一下 

```js
const now = Date.now()
setTimeout(() => console.log(Date.now() - now), 1000)
```

**Comment by hobmgcode** [comment]
封号！
