### ISSUE TITLE
我最在行辅助设置任何主题都为春节题目

### ISSUE THREAD

**Issue by SuperLangdon** [game-helper/weixin#36]
如题
![qq 20180225195037](https://user-images.githubusercontent.com/21187253/36641075-36a505d8-1a65-11e8-9398-55a1abc5ded8.png)

**Comment by zhuweiyou** [comment]
参数漏传了，重新下载最新代码试一下。

有问题再反馈

**Comment by SuperLangdon** [comment]
我测试了下 还是一样

**Comment by zhuweiyou** [comment]
你是否有打过其它擂台？截图看下你的手机

**Comment by SuperLangdon** [comment]
有打过其他擂台 手机是小米5 基于安卓7.0的MIUI
![_20180225224847](https://user-images.githubusercontent.com/21187253/36642674-1a392564-1a7e-11e8-93a8-e3fd306b754c.png)

**Comment by zhuweiyou** [comment]
填 1 呢
