### ISSUE TITLE
请教下，WSS是通过什么抓包的呀？

### ISSUE THREAD

**Issue by Tangtonton** [game-helper/weixin#48]
现在WSS的游戏很多，可是用Fiddler好像抓不到？？

**Comment by zhuweiyou** [comment]
逆向

**Comment by Tangtonton** [comment]
谢谢。。其实没什么特别，只是自己想把那几个答题游戏也做成wss的。发现自己只能发个post get之类的:grin

那 wireshark 可以抓到 wss 吗。。还是说把小程序下载下来解密:broken_heart

**Comment by zhuweiyou** [comment]
wireshark 理论上可以，但是如果是密文通讯，一样无解。

**Comment by Tangtonton** [comment]
在网上找到个方法，解压了源码。。就算把代码美化后也很难看懂。。应该是被混淆过的吧。。。

**Comment by CL545740896** [comment]
微信小游戏自带的一个API   Wx.setUserStorge()   把小游戏的源码下载了下来编译发现 是websocket通讯的，我用wireshark好像抓不到这个websocket，请教一下怎样能抓到这个websocket
