### ISSUE TITLE
加入请求

### ISSUE THREAD

**Issue by clouduan** [game-helper/weixin#53]
大佬们好，我自己也做过一个 微信小程序-加件大师 的游戏辅助，虽然实现原理简单但是可以成功。

我自己刚也准备建了一个 organization，想专门手机 微信小程序的辅助，搜了一下发现你们已经做了这个。

请问我可以加入此组织吗？（我比较喜欢加 organization :neckbeard:

**Comment by zhuweiyou** [comment]
可以，欢迎加入。但是时间原因，目前无精力维护此项目。
正想寻求人来主力开发，给你个权限，你加入进来吧？

**Comment by clouduan** [comment]
好的，thanks

**Comment by clouduan** [comment]
Done :heavy_check_mark:
