### ISSUE TITLE
关于加减大师识别判断结果BUG  我可能是太菜了 0_V_0

### ISSUE THREAD

**Issue by JackyLove01** [game-helper/weixin#60]
首先在pymouse模块上折腾了一段时间 之后运行脚本时 除了第一运行正常，接下来的数次都有问题，具体现象是程序一直选择 “”FALSE“”？？？但是 每个字符都识别正常！！！

![Uploading TIM截图20190402182257.png…]()

**Comment by voldikss** [comment]
@JackyLove01 试试这个 https://github.com/voldikss/WechatGameAutoPlayer

这里的好久没更新了，当时做得很渣

**Comment by JackyLove01** [comment]
> @JackyLove01 试试这个 https://github.com/voldikss/WechatGameAutoPlayer
> 
> 这里的好久没更新了，当时做得很渣

OK

**Comment by voldikss** [comment]
@JackyLove01 可以关闭这个 issue了
